Reworking main UI
pharo-spec/Chest pull request #23
Opened 2023-08-02 13:22 UTC by adri09070

Cleaner UI:

- Adding informations
  * for each chest, its size is now displayed
  *  for each item of a chest, its name, value and class are displayed

![image](https://github.com/pharo-spec/Chest/assets/97704417/d736f160-cce4-4e09-9d68-1c114785231a)

- Actions are now disabled when they should be:

![image](https://github.com/pharo-spec/Chest/assets/97704417/be1b410e-5d30-4387-9087-e255cd8e0aa1)

- shorter toolbar
  * "Remove all chests" and "remove all items" actions have been moved to their respective contextual menu.

- adding actions:
  * "Inspect chest" via the chest table's contextual menu
  * "Add chest" is still in the chest's toolbar but is now also in the associated context menu
  * new action "Add item" that opens a pop-up to enter an expression whose result will be stored in the selected chest:
    
    Before validating the expression:

    ![before validating expression](https://github.com/pharo-spec/Chest/assets/97704417/ceefec03-6b3b-43c0-84d8-bfa06a5fd830)

    After validating the expression:

    ![after validating expression](https://github.com/pharo-spec/Chest/assets/97704417/1b847c21-f4fe-4ee6-9b55-a4746ca11cd4)

- custom expandable views, which can be configured via the system settings and/or class settings (and thus via a script):

View without playground or inspector: 

![View without playground or inspector](https://github.com/pharo-spec/Chest/assets/97704417/8eb063ba-fd42-4e31-a1b3-c856ccc632d2)

View with playground only:

![View with playground only](https://github.com/pharo-spec/Chest/assets/97704417/3d2208d8-cb2c-4da9-9c23-dd7307ab2f6f)

View with inspector only:

![View with inspector only](https://github.com/pharo-spec/Chest/assets/97704417/7341fbdb-400a-4c8a-8dcc-09dc995c66a5)

View with playground + inspector:

![View with playground and inspector](https://github.com/pharo-spec/Chest/assets/97704417/0de4a69e-0835-4b7d-b4f2-19697d7403fd)

- The playground is now pre-filled with code, illustrating briefly how to use Chest's API:

![View with playground only](https://github.com/pharo-spec/Chest/assets/97704417/3d2208d8-cb2c-4da9-9c23-dd7307ab2f6f)

2023-08-02 13:30 UTC, adri09070 commented
I reworked fully only the main UI, and not the secondary views (e.g: store / load popup layouts, tree table view).

I think their rework deserve their own PR

2023-08-02 14:21 UTC, adri09070 commented
Looks like unrelated tests.

Maybe the random failure in NewTools should have a fix though

2023-08-03 08:34 UTC, StevenCostiou requested changes

2023-08-03 08:34 UTC, StevenCostiou commented on src/Chest/ChestPresenter.class.st
> +	^ ShowInspector := anObject
setters should not return anything specific

2023-08-03 08:34 UTC, StevenCostiou commented on src/Chest/ChestPresenter.class.st
> +	^ ShowPlayground := anObject
setters should not return anything specific

2023-08-03 08:34 UTC, StevenCostiou commented on src/Chest/ChestPresenter.class.st
> +	"showInspectorContainer remove: inspector."
remove comment

2023-08-03 08:34 UTC, StevenCostiou commented on src/Chest/ChestPresenter.class.st
>  ChestPresenter >> iconManager [
What is the icon manager?

2023-08-03 08:34 UTC, StevenCostiou commented on src/Chest/ChestTableWithContentPresenter.class.st
> +					                       association value class printString ])
Are we looking for the class name?
It is better to get it using `class name` rather than `printString`, unless printing provides more info.
The problem I see is that the implementation of print string for classes can change (maybe it will never do) and print others things, while it looks like we always want the name.

2023-08-03 08:36 UTC, adri09070 commented on src/Chest/ChestPresenter.class.st
> +	^ ShowInspector := anObject
indeed, the "generate accessors" refactoring did that

2023-08-03 08:43 UTC, adri09070 commented on src/Chest/ChestPresenter.class.st
>  ChestPresenter >> iconManager [
Something that should disappear, I guess: it has no senders

2023-08-03 08:56 UTC, merged