Fixing #selectedChest when selecting an item in the tree table view
pharo-spec/Chest pull request #34
Opened 2024-04-23 12:11 UTC by adri09070

2024-04-30 13:10 UTC, adri09070 commented
@StevenCostiou

2024-05-03 10:13 UTC, StevenCostiou requested changes
Changes are good, some comments that should be answered prior to merge.

2024-05-03 10:13 UTC, StevenCostiou commented on src/BaselineOfChest/BaselineOfChest.class.st
> +	chestClass := self class environment at: #Chest.
Should we not return from the method if the Chest class is absent from the environment?
There is the possibility that someones calls this code only from the baseline, without having charged the project.

2024-05-03 10:13 UTC, StevenCostiou commented on src/Chest/ChestTableWithContentPresenter.class.st
>  	items := activePresenter == chestWithContentTreeTable
I do not see clearly how the code works, it seems that seometimes the `activePresenter` can be nil (possibly a constraint from Spec?). However in one case (line 922) when testing if `activePresenter == chestWithContentTreeTable` there is a nil check over `activePresenter` first and in the other case (line 803) there is no nil check.

Shouldn't the nil check be also present line 803?

2024-05-03 11:30 UTC, adri09070 commented on src/BaselineOfChest/BaselineOfChest.class.st
> +	chestClass := self class environment at: #Chest.
done

2024-05-03 11:32 UTC, adri09070 commented on src/Chest/ChestTableWithContentPresenter.class.st
>  	items := activePresenter == chestWithContentTreeTable
I did it on line 922 because `#selectedChest` is a method called by commands in their `#canBeExecuted` method and `activePresenter` is not initialized at that moment. 

In line 922, this is ok, this method is called when the user clicks a button, which implies that the presenter is already initialized and that `activePresenter` is not nil

2024-05-06 13:59 UTC, StevenCostiou approved these changes

2024-05-06 13:59 UTC, merged